<?php
$congfig='asd';
$admin='cheek';


thunder://QUFtYWduZXQ6P3h0PXVybjpidGloOkM1M0VFNkYxMzg5RjNDQ0VENjBDNDcxMDVBMDZGMUM4MkNGRURDRTUmZG49JWU4JTg3JWFhJWU2JTlkJTgwJWU1JWIwJThmJWU5JTk4JTlmJTIwU3VpY2lkZSUyMFNxdWFkWlo=/
